In [1]:
import numpy as np

#difference between a Python list and a NumPy array
python_list = list(range(5))
numpy_array = np.array(range(5))
python_list, numpy_array

([0, 1, 2, 3, 4], array([0, 1, 2, 3, 4]))

In [2]:
#Numpy 1D array generation
inclusive_begin = 3
exclusive_end = 10
np.arange(inclusive_begin, exclusive_end)

array([3, 4, 5, 6, 7, 8, 9])

In [6]:
# or better with float instead of integer?
np.linspace(inclusive_begin, exclusive_end, 5)

array([ 3.  ,  4.75,  6.5 ,  8.25, 10.  ])

In [9]:
#NumPy 1D+ Array Generation
size = (1, 2, 3) # Could also be (1, 2) or (4, 3, 2, 1, ...), etc. 
np.random.random_sample(size=size)

array([[[0.57969156, 0.03327825, 0.42382917],
        [0.69427373, 0.86632667, 0.78309471]]])

In [14]:
# let's try with only ones
np.ones(5)

array([1., 1., 1., 1., 1.])

In [13]:
#or with only zeros
np.zeros(4)

array([0., 0., 0., 0.])