## Exercice 5: Utilisation de l'aide en ligne

In [3]:
# -*- coding: utf-8 -*-
"""
Created on Tue Jan  3 12:52:30 2023

@author: T14
"""

# importing numpy library
import numpy as np
  
# create numpy 2d-array
mat5 = np.array([[1, 2], [2, 3]])
  
print("Printing the Original square array:\n", mat5)

Printing the Original square array:
 [[1 2]
 [2 3]]


In [3]:
# finding eigenvalues and eigenvectors
w, v = np.linalg.eig(mat5)
  
# printing eigen values
print("Printing the Eigen values of the given square array:\n", w)

Printing the Eigen values of the given square array:
 [-0.23606798  4.23606798]


In [ ]:
# finding Vandermonde array


In [4]:
# Longueur d'un vecteur
vec = np.array([1,3,6,9,12,15,20,22,25])
print(vec.size)

9


In [5]:
# Taille d'une matrice
arr = np.array([[1,3,6],[9,12,15],[20,22,25]])
print(arr.shape)

(3, 3)


In [6]:
# Temps d'exécution dun programme

# import the time module
import time

# get the current time in seconds since the epoch (the point where time begins)
seconds = time.time()

print("Seconds since epoch =", seconds)	

Seconds since epoch = 1672763502.2289653


In [1]:
# Donner une matrice circulaire
# import the scipy package
from scipy.linalg import circulant

A = circulant([1, 2, 3])
print(A)

[[1 3 2]
 [2 1 3]
 [3 2 1]]


In [13]:
B = np.random.rand(2, 5)
print(B)


[[0.72414611 0.04465199 0.52750393 0.25112123 0.09535369]
 [0.07428194 0.48794117 0.16942439 0.24240602 0.59718417]]
